"use strict";
const brand = require("./customer-brand");
const page = `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>OHCAYGO Merge Proof</title>
<style>${brand.css}</style><body class="brand-page proof-page">${brand.header}<main id="main">
<header class="proof-intro"><p class="eyebrow">HOSTED MERGE PROOF</p><h1>PROVE THE MERGE.</h1><p>Verify the GitHub-reported candidate and, when GitHub can bind it, what landed.</p></header>
<section id="welcome" class="trial-card"><h2>TRY MERGE PROOF FREE</h2><p><strong>7-day hosted, report-only trial from your first successful proof. No card required.</strong></p><p>You'll need a GitHub account, a repository you can authorize, and an open PR for your first live proof. If none is open, we watch for the next one.</p><p>Connect GitHub so we can show repositories you can access. Then install the App on the repositories you choose. We read repository evidence and publish receipt Checks on GitHub.</p><p>Continue afterward for $29/month per active developer. Otherwise new hosted proofs, re-proofs and scans pause without an automatic charge; existing receipts remain available with current authorization, subject to retention and capacity limits. New enforcing gates require paid Pro.</p><details><summary>What starts the trial?</summary><p>A successful proof means evidence collection completed for the current observed state: a CURRENT, collection-complete VERIFIED or NOT_PROVEN hosted receipt. NOT_PROVEN can mean missing, ambiguous, unsupported or unavailable evidence; it does not mean your code is broken. FAIL, unavailable or stale collection does not start your trial. Connecting GitHub, installing the App, authorizing repositories and historical scans do not start it either. One 7-day trial starts exactly once per paying account.</p></details><p><a id="connect" class="primary" href="/proof/login">CONNECT GITHUB</a></p><p>Install and authorize once. Merge Proof finds open PRs and starts proving automatically. Choose an account or repository only where needed. “Prove it now” is optional; provider, permission and capacity limits can require attention.</p><p>Prefer local? <a href="https://github.com/ohcaygo/merge-proof#readme">Free CLI + GitHub Action →</a></p></section>
<p id="status" role="status">Checking your GitHub connection…</p><p id="retrySession" hidden><button id="retryConnection">Retry connection</button></p>
<section id="connected" hidden><h2>Connected repositories</h2><p id="installHelp">GitHub is connected and App installations were found. Choose an account to check its authorized repositories, or install the App on another repository.</p><a id="install" class="primary" hidden>INSTALL ON SELECTED REPOSITORIES</a><button id="reloadInstallations">Refresh connected repositories</button><p><label>GitHub account <select id="installation"><option value="">Select account</option></select></label></p><p id="repositoryChoice" hidden><label>Repository <select id="repository" disabled><option value="">Select repository</option></select></label></p><p>Uninstall or change repository access in GitHub App settings. Uninstall stops new proofs and denies hosted receipt access; accounting history is preserved for reconnect.</p></section>
<div id="workspace" hidden><aside class="trial-status" aria-label="Trial and hosted access"><h2 id="trialLabel">Checking hosted access</h2><p id="trialDetail"></p><a href="#billing">Account / Continue Pro — $29 per active developer</a><details><summary>Exact entitlement details</summary><p id="usage"></p></details></aside>
<section id="firstProof"><h2>Latest proof observations</h2><p>Merge Proof runs in the background. You can close this page. We will automatically check authorized PR activity.</p><p class="small">GitHub Checks are the result surface; this page is an optional account view, not another merge gate. Provider access, delivery and evidence limits can require attention. Signing out of this website does not uninstall the App or delete tracked work.</p><p id="monitoring" role="status">Checking automatic proof status</p><p id="noPulls" hidden>No open PRs yet. Merge Proof will watch for the next one automatically.</p><p id="inboxEmpty" hidden>No hosted observation is available for the open PRs yet. Checking current evidence does not mean a current proof has been established.</p><p><label><input id="latestOnly" type="checkbox" checked> Latest only — expand each card to inspect its history</label></p><ul id="receipts"></ul><details class="manual-controls"><summary>Optional manual recovery</summary><p>These controls are not required for normal background operation. Refresh reads account information; “Prove it now” collects a new observation. Neither fixes unchanged evidence limits or permissions.</p><button id="refresh">Refresh account information</button><label>Open pull request <select id="pull"></select></label><button id="refreshPulls">Refresh open PR information</button><button id="run" disabled>Optional: prove it now</button></details></section>
<section id="enhancedSection"><h2>Optional Enhanced Policy Proof</h2><p>The Standard App uses Administration Read. Some GitHub workflow execution-policy details require Administration Write to read. Optional Enhanced Policy Proof uses a separately authorized, repository-bound policy reader for those reads only; it does not change repository administration.</p><p>This is a powerful GitHub grant: a stolen credential still has Write authority. The isolated reader rejects administration mutations. If this optional reader is unavailable, or GitHub cannot provide a needed policy detail, the affected policy or coverage claim remains NOT_PROVEN.</p><p id="enhancedStatus" role="status">Select a repository to check this optional capability.</p><label><input id="enhancedConsent" type="checkbox"> I authorize the separate companion App to read execution policies for this repository with Administration Write.</label><p><button id="enableEnhanced">Enable / connect Enhanced Policy Proof</button> <button id="disableEnhanced">Turn off Enhanced Policy Proof</button> <button id="refreshEnhanced">Refresh capability status</button></p><p>Turning this off stops enhanced reads and rechecks dependent claims; it does not uninstall the companion. Remove its repository access in GitHub to revoke the provider grant. Historical receipts stay unchanged.</p></section>
<section id="gateSection"><h2>Require Merge Proof before merge</h2><p>Merge Proof defaults to report-only. Installing it does not configure a required GitHub gate. New enforcing policies require paid Pro and a repository administrator; GitHub must separately require the correct Merge Proof Check. Merge Proof never edits branch protection or rulesets. A passing policy Check is not necessarily a VERIFIED receipt.</p><p id="gateStatus">Select a repository to see whether Merge Proof is required.</p><pre id="gateReadiness"></pre><details><summary>How to require it in GitHub</summary><ol id="gateSteps"></ol><p id="gateNotes"></p></details><p><label>What should Merge Proof's check do? <select id="preset"></select></label></p><button id="savePolicy">Save policy</button><button id="refreshGate">Refresh gate status</button><p id="policyNote">Merge Proof never edits your branch protection or rulesets. Changing this setting needs repository admin.</p></section>
<section id="mergesSection"><h2>Merge records</h2><p>Pre-merge evidence held when the merge event arrived. When GitHub content can be bound, the record connects that receipt to landed content; exact decision-time currentness is still reported as unavailable. These records are kept as they were; later evidence does not rewrite them.</p><p><label>Filter <select id="mergeVerdict"><option value="">All results</option><option value="VERIFIED">VERIFIED</option><option value="NOT_PROVEN">NOT_PROVEN</option><option value="FAIL">FAIL</option><option value="NO_PROOF">No proof recorded</option></select></label> <button id="refreshMerges">Refresh</button></p><ul id="merges"></ul><p id="mergeCompleteness"></p></section>
<section><h2>Optional free historical scan</h2><p>See how Merge Proof evaluates evidence from recent merges in this repository.</p><p>One free scan: up to 5 merged PRs from the 30 most recently updated closed PRs. Squash/rebase history is unsupported; current rules cannot prove historical approvals. This does not start your trial clock.</p><button id="scan">Start / retry same scan</button><button id="skip">Go to live proof</button><button id="cancelScan">Cancel scan</button><button id="scanStatus">Refresh scan progress</button><pre id="scanResult"></pre></section>
<section id="billing"><h2>Pro — $29/month per active developer</h2><p>Hosted proofs and automatic re-proofs are included. We count distinct human GitHub IDs opening covered PRs or pushing covered commits during the subscription month. Bots are excluded; human attribution requires GitHub evidence. Initial count uses the last 30 days of observed covered activity.</p><pre id="developers"></pre><p>Pro continues after verified payment. No automatic charge at trial expiry. Quantity increases require your confirmation; no proration. Decreases apply at renewal.</p><button id="subscribe">Continue Pro — $29 per active developer</button><button id="quantity">Confirm active-developer quantity for renewal</button><button id="portal">Manage subscription</button></section></div>
<p id="sessionControls" hidden><button id="logout">Disconnect this session</button></p></main><footer><p>Questions? <a href="mailto:support@ohcaygo.com">support@ohcaygo.com</a></p></footer><script src="/proof/app.js"></script></body></html>`;
const script = `"use strict";
const $=id=>document.getElementById(id);let account;let selectionVersion=0;let sessionEstablished=false;
const accountView=new URLSearchParams(location.search).get('view')==='account'||new URLSearchParams(location.search).has('checkout');
let returnScope={installation:new URLSearchParams(location.search).get('installation'),repository:new URLSearchParams(location.search).get('repository')};
const scope=()=>({installation:Number($("installation").value),repository:Number($("repository").value)});
async function api(path,body){const r=await fetch('/proof/'+path,{...(body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});const d=await r.json();if(!r.ok&&d.error==='LOGIN_REQUIRED')errorStatus(Error('LOGIN_REQUIRED'));if(!r.ok)throw Error(d.error==='CHECK_RECONCILIATION_PENDING'?'Policy saved, but GitHub check updates are pending. Do not rely on the gate yet; Merge Proof will retry.':d.error==='GATE_NOT_READY'?'Policy was not changed. Keep existing protections and resolve the readiness items below before enabling a blocking policy.':d.error);return d;}
function status(s){$('status').textContent=s;}
const source=new URLSearchParams(location.search).get('source');if(['x','other','direct'].includes(source))$('connect').href='/proof/login?source='+source;
function errorStatus(e){if(e.message==='LOGIN_REQUIRED'){++selectionVersion;resetSelection();$('installation').replaceChildren();$('installation').value='';$('install').hidden=true;$('workspace').hidden=true;$('connected').hidden=true;$('welcome').hidden=false;$('sessionControls').hidden=true;$('connect').textContent='CONNECT GITHUB';$('connect').href='/proof/login'+(['x','other','direct'].includes(source)?'?source='+source:'');status(sessionEstablished?'Your website session expired or is unavailable. Connect GitHub again to view your account. GitHub may require login or two-factor authentication. App installation and repository access will be checked after login. This does not uninstall the App, stop existing tracked background work, or restart your trial.':'Connect GitHub to view your authorized repositories. We will check your App installation and repository access after sign-in. Existing background proofs keep running.');return;}status(e.message);}
let sessionTimer;
function resetSelection(){account=null;$('repositoryChoice').hidden=true;$('repository').disabled=true;$('repository').replaceChildren();$('repository').value='';$('run').disabled=true;$('workspace').hidden=true;}
function sessionDeadline(expiresAt){if(!Number.isFinite(expiresAt))return true;if(typeof clearTimeout==='function')clearTimeout(sessionTimer);const remaining=expiresAt-Date.now();if(remaining<=0){errorStatus(Error('LOGIN_REQUIRED'));return false;}if(typeof setTimeout==='function')sessionTimer=setTimeout(()=>errorStatus(Error('LOGIN_REQUIRED')),remaining);return true;}
function bind(id,fn){$(id).onclick=()=>Promise.resolve().then(fn).catch(e=>status(e.message==='TRIAL_EXPIRED'?'Hosted access ended — automation paused. New proofs, re-proofs and scans are paused; existing receipts remain available with current authorization and retention limits. Continue Pro for $29/month per active developer. If GitHub requires Merge Proof, subscribe or remove the required check; Merge Proof never changes your rules.':e.message==='LOGIN_REQUIRED'?(errorStatus(e),$('status').textContent):e.message));}
function option(select,value,text){const o=document.createElement('option');o.value=value;o.textContent=text;select.append(o);}
async function load(){const version=++selectionVersion;const q=new URLSearchParams(scope());$('workspace').hidden=true;$('run').disabled=true;if(!scope().installation||!scope().repository)return;let next;try{next=await api('account?'+q);}catch(e){if(version===selectionVersion)errorStatus(e);return;}if(version!==selectionVersion)return;account=next;$('workspace').hidden=false;const u=account.usage;$('usage').textContent=u.notice;$('developers').textContent=account.billingOwner?u.activeDevelopers.length+' active developers · expected $'+(29*u.activeDevelopers.length)+'/month\\n'+u.activeDevelopers.map(d=>d.login+': '+d.activity.map(a=>a.kind+' at '+new Date(a.at).toISOString()).join(', ')).join('\\n'):"Your account's billing owner can review the active-developer count and subscription total. Pro is $29/month per active developer.";for(const id of ['subscribe','quantity','portal'])$(id).hidden=!account.billingOwner;$('pull').replaceChildren();for(const p of account.pulls)option($('pull'),p.number,'#'+p.number+' '+p.title);$('noPulls').hidden=account.pulls.length>0;$('pull').disabled=!account.pulls.length;$('run').disabled=!account.pulls.length||!u.automationAllowed;$('scan').disabled=!u.automationAllowed;$('monitoring').textContent=account.automation.message;renderInbox(account.inbox||[]);const trial=account.trialStatus||{label:'Hosted access',detail:u.notice};$('trialLabel').textContent=trial.label;$('trialDetail').textContent=trial.detail;renderMerges(account.merges);renderEnhanced(account.enhancedPolicy);gate(false).catch(()=>{$('gateStatus').textContent='Could not read the merge-gate status for this repository right now.';});status(new URLSearchParams(location.search).has('checkout')&&u.plan!=='PRO'?'Confirming subscription. Access changes only after verified payment; refresh to check.':u.automationAllowed?account.automation.message:u.notice);}
function renderEnhanced(v){v=v||{configured:false,state:'OFF',admin:false};$('enhancedStatus').textContent=!v.configured?'Enhanced Policy Proof is not available for this service. Standard Read remains active.':'Capability: '+v.state+(v.checkedAt?' · Last checked '+v.checkedAt:'')+'. Enabling the capability is not a VERIFIED verdict.';$('enableEnhanced').disabled=!v.configured||!v.admin;$('disableEnhanced').disabled=!v.admin||v.state==='OFF';$('enhancedConsent').disabled=!v.configured||!v.admin;}
async function refreshEnhanced(){const version=selectionVersion,d=await api('enhanced?'+new URLSearchParams(scope()));if(version===selectionVersion)renderEnhanced(d);}
bind('refreshEnhanced',refreshEnhanced);
bind('enableEnhanced',async()=>{if(!$('enhancedConsent').checked)throw Error('Explicit consent is required for the separate Administration Write companion.');const version=selectionVersion,d=await api('enhanced',{...scope(),action:'enable',consent:true});if(version!==selectionVersion)return;renderEnhanced(d);$('enhancedConsent').checked=false;status(d.enabled?'Enhanced policy reads are enabled. Claims still require sufficient current evidence.':'Continue in GitHub to approve the companion installation.');if(d.installUrl){const u=new URL(d.installUrl);if(u.origin!=='https://github.com'||!new RegExp('^/apps/[a-z0-9-]+/installations/new$').test(u.pathname))throw Error('Invalid companion installation destination');location.assign(u.href);}});
bind('disableEnhanced',async()=>{const version=selectionVersion,d=await api('enhanced',{...scope(),action:'disable'});if(version===selectionVersion){renderEnhanced(d);$('enhancedConsent').checked=false;status('Enhanced policy reads are off. Dependent claims will be rechecked.');}});
function textElement(tag,text){const e=document.createElement(tag);e.textContent=text;return e;}
function receiptLink(r,label){const a=document.createElement('a');a.href='/proof/receipts/'+r.id;a.textContent=label;return a;}
const expandedHistory=new Set();
function renderInbox(cards){$('receipts').replaceChildren();$('inboxEmpty').hidden=cards.length>0;for(const r of cards){const li=document.createElement('li');li.append(textElement('h3',r.repository+' · PR #'+r.pr+(r.title?' — '+r.title:'')));const badges=document.createElement('p');badges.className='proof-badges';for(const label of ['Verdict: '+r.label,'Freshness: '+r.freshness]){const b=textElement('span',label);b.className='badge';badges.append(b);}li.append(textElement('p',r.explanation),badges,textElement('p','Merging: '+r.mergeImpact),textElement('p','Next action: '+r.nextAction),textElement('p','Automatic re-check: '+r.automation.text),textElement('p','Observed: '+r.observedAt+(r.currentnessObservedAt?' · Currentness last checked: '+r.currentnessObservedAt:'')),textElement('p',r.freshnessDetail));if(r.id)li.append(receiptLink(r,'Open latest receipt'));if(r.history.length){const details=document.createElement('details');const key=r.repository+':'+r.pr;details.open=!$('latestOnly').checked||expandedHistory.has(key);details.ontoggle=()=>{if(details.open)expandedHistory.add(key);else expandedHistory.delete(key);};details.append(textElement('summary',r.history.length+' previous observations — immutable history'));const list=document.createElement('ul');for(const old of r.history){const item=document.createElement('li');item.append(receiptLink(old,old.observedAt+' · '+old.label+' · '+old.freshness));list.append(item);}details.append(list);li.append(details);}$('receipts').append(li);}}
$('latestOnly').onchange=()=>{expandedHistory.clear();renderInbox(account?.inbox||[]);};
$('installation').onchange=async()=>{const version=++selectionVersion;resetSelection();option($('repository'),'','Select repository');if(!scope().installation){status('GitHub connected. Choose an installed account to check repository authorization.');return;}status('GitHub connected. Checking authorized repositories for this installation…');try{const d=await api('repositories?installation='+scope().installation);if(version!==selectionVersion||!sessionDeadline(d.sessionExpiresAt))return;for(const r of d.repositories)option($('repository'),r.id,r.name);$('repository').disabled=!d.repositories.length;$('repositoryChoice').hidden=!d.repositories.length;const selected=d.repositories.find(r=>String(r.id)===returnScope.repository&&String(scope().installation)===returnScope.installation)||(d.repositories.length===1?d.repositories[0]:null);returnScope={};if(selected){$('repository').value=selected.id;await load();return;}status(d.repositories.length?'Choose a repository.':'No authorized repositories found. Install the App on a repository you can authorize, then refresh connected repositories.');}catch(e){if(version!==selectionVersion)return;resetSelection();if(e.message==='LOGIN_REQUIRED')errorStatus(e);else{status('GitHub is connected, but repository authorization could not be verified. Refresh connected repositories to retry.');}}};
$('repository').onchange=()=>load().catch(errorStatus);
async function gate(save){const q=new URLSearchParams(scope());if(!scope().installation||!scope().repository)return;const d=save?await api('gate',{...scope(),preset:$('preset').value}):await api('gate?'+q);const s=d.status;$('gateStatus').textContent=s.required===true?'Merge Proof IS a required check on '+s.branch+(s.boundToThisApp===true?', bound to this App.':', but not bound to a specific App.'):s.required===false?'Merge Proof is NOT required on '+s.branch+' yet. Nothing is blocked by it.':'Could not read the rules for '+s.branch+'.';$('gateReadiness').textContent=s.readiness.state==='READY'?'Ready: this branch requires '+s.independentRequiredChecks+' check(s) and '+s.approvalsRequired+' approval(s) that Merge Proof can prove.':s.readiness.blockers.map(b=>b.plain+'\\n  '+b.doNext).join('\\n');$('gateSteps').replaceChildren();for(const step of d.instructions.steps){const li=document.createElement('li');li.textContent=step;$('gateSteps').append(li);}$('gateSteps').closest('details').hidden=!d.enforcementAvailable&&s.required!==true;$('gateNotes').textContent=d.instructions.prerequisite+' '+d.instructions.whyBothSteps+' '+d.instructions.permissionsNote;if(!$('preset').options.length)for(const p of d.presets)option($('preset'),p.id,p.label+' — '+p.description);$('preset').value=d.policy.preset;for(const o of $('preset').options){const p=d.presets.find(p=>p.id===o.value);o.disabled=p.enforced&&!d.enforcementAvailable;}$('preset').disabled=!d.admin;$('savePolicy').disabled=!d.admin;$('policyNote').textContent=(d.admin?'':'Only a repository admin can change this. ')+'Merge Proof never edits your branch protection or rulesets. The trial does not enable new enforcing policies. Previously configured enforcing policies remain enforced. If hosted access expires, they report failure; report-only notices are neutral. If GitHub requires the check, subscribe or remove that required check. Provider or permission failures can prevent delivery; automatic unblocking is not guaranteed. '+d.trialNotice;if(save)status('Policy saved: '+d.policy.label+'.');}
function renderMerges(d){$('merges').replaceChildren();for(const m of d.records){const li=document.createElement('li');li.textContent='PR #'+m.pr+' · merged '+(m.mergedAt||'unknown')+' · '+m.verdict+(m.boundToMergedState?' for the merged commit':' (exact landed-state binding not established)')+' · landed '+(m.landed?.state||'LANDED_UNRESOLVED')+' · currentness at merge '+m.currentnessAtMerge+' · merged by '+m.mergedBy+' · authorship '+m.agentIdentity+(m.gateEnforced?' · gate '+m.gateConclusion:'');if(m.receiptId){const a=document.createElement('a');a.href='/proof/receipts/'+m.receiptId;a.textContent=' view receipt';li.append(a);}$('merges').append(li);}$('mergeCompleteness').textContent=d.total+' record(s). '+d.completeness;}
async function merges(){const q=new URLSearchParams(scope());const v=$('mergeVerdict').value;if(v)q.set('verdict',v);renderMerges(await api('merges?'+q));}
bind('savePolicy',()=>gate(true));bind('refreshGate',()=>gate(false));bind('refreshMerges',merges);
bind('refresh',load);bind('refreshPulls',load);bind('run',async()=>{if(!Number($('pull').value))return;$('run').disabled=true;status('Collecting evidence. Your receipt will open when ready…');try{const d=await api('run',{...scope(),pr:Number($('pull').value)});location.href=d.url;}finally{$('run').disabled=false;}});
bind('scan',async()=>{await api('scan',scope());status('Scan started. Refresh scan progress to see results.');});bind('scanStatus',async()=>{$('scanResult').textContent=JSON.stringify(await api('scan?'+new URLSearchParams(scope())),null,2);});bind('cancelScan',async()=>{await api('scan/cancel',scope());status('Scan cancellation requested.');});bind('skip',()=>{$('firstProof').scrollIntoView();});
bind('subscribe',async()=>{const n=account.usage.activeDevelopers.length;if(!account.billingOwner){status('Only the paying account owner can manage billing.');return;}if(!n){status('No human covered activity observed yet. Open a covered PR or push a covered commit, then refresh.');return;}if(confirm('Continue Pro for '+n+' active developers at $'+29*n+'/month?'))location.href=(await api('checkout',{...scope(),kind:'pro',quantity:n})).url;});
bind('quantity',async()=>{const n=account.usage.activeDevelopers.length;if(confirm('Set the next monthly invoice to '+n+' developers at $'+29*n+'? No current-period proration.')){const d=await api('quantity',{...scope(),quantity:n});status(d.message+' Effective: '+d.effectiveAt);}});
bind('portal',async()=>{location.href=(await api('portal',scope())).url;});bind('logout',async()=>{await api('logout',{});location.href='/proof/';});
async function installations(){const version=++selectionVersion;resetSelection();$('connected').hidden=true;$('sessionControls').hidden=true;status('Checking GitHub authentication and App installations…');let d;try{d=await api('installations');}catch(e){if(version!==selectionVersion)return;throw e;}if(version!==selectionVersion||!sessionDeadline(d.sessionExpiresAt))return;sessionEstablished=true;$('sessionControls').hidden=false;$('retrySession').hidden=true;if(!accountView){$('connect').href='/proof/?view=account';$('connect').textContent='CONTINUE TO CONNECTED REPOSITORIES';status('GitHub is connected. Read the trial information, then continue when you are ready.');return;}$('welcome').hidden=true;$('connected').hidden=false;$('installation').replaceChildren();option($('installation'),'','Select account');for(const i of d.installations)option($('installation'),i.id,i.account);if(d.installUrl){$('install').href=d.installUrl;$('install').hidden=false;}$('installHelp').textContent=d.installations.length?'GitHub is connected and App installations were found. Choose an account to check its authorized repositories, or install the App on another repository.':'Install the GitHub App on a repository you can authorize. Return here after installation and refresh connected repositories.';status(d.installations.length?'GitHub connected. App installation found. Choose an account to check repository authorization.':'GitHub connected. Install the App on selected repositories to continue.');const selected=d.installations.find(i=>String(i.id)===returnScope.installation)||(d.installations.length===1?d.installations[0]:null);if(selected){$('installation').value=selected.id;await $('installation').onchange();}}
setInterval(()=>{if(accountView&&!document.hidden&&scope().repository)load().catch(errorStatus);},30000);bind('reloadInstallations',installations);
async function restoreSession(){try{await installations();}catch(e){$('welcome').hidden=false;$('connected').hidden=true;$('workspace').hidden=true;$('sessionControls').hidden=true;$('retrySession').hidden=e.message==='LOGIN_REQUIRED';if(e.message==='LOGIN_REQUIRED')errorStatus(e);status(e.message==='LOGIN_REQUIRED'?'Connect GitHub to view your authorized repositories. We will check your App installation and repository access after sign-in. Existing background proofs keep running.':'Could not restore your GitHub connection. Retry, or return to trial information.');}}
bind('retryConnection',restoreSession);if(typeof addEventListener==='function')addEventListener('pageshow',e=>{if(e.persisted)restoreSession();});restoreSession();`;
// The URL, not authentication or a late response, owns the visible step.
function renderPage(url) {
  return url.searchParams.get("view") === "account" || url.searchParams.has("checkout")
    ? page.replace('id="welcome" class="trial-card"', 'id="welcome" class="trial-card" hidden')
    : page;
}
module.exports = { page, script, renderPage };
